import type { NextPage } from 'next';
import Head from 'next/head';
import { signIn, signOut, useSession } from 'next-auth/client';

const Home: NextPage = () => {
  const [session, loading] = useSession();

  return (
    <div>
      <Head>
        <title>Next Enterprise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-6xl">Next.js Enterprise</h1>
      <p>This project is powered by `next-auth`, prisma and WorkOS</p>

      {session && (
        <>
          Signed in as {session.user.email} <br />
          <button onClick={() => signOut()}>Sign out</button>
        </>
      )}
      {/* add steps here + include video */}
    </div>
  );
};

export default Home;
